ssh_pwauth: no
users:
  - name: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCereJ4ZnvDSrCVwY+C6ZZoBxEKgiClct5e76a2DGI2ltjE0Pqd1wyvGSOmSpCQEraHnPn+CAvVSCUMFyK4+uPq571Gpfyyi39l07hLged+rWCuiaRSel5wYDuxsRNWzhkoOTs/NiIXHzJ+e9PURqp+eROja1CR/AQtSBEyeqUjB5wTgWYyFgyviEbMpmsS3Y7eP0zVrAT0IiTDcxbDDp09lKiUx3wju9cq/SoQ/RAlFH92bdZi+bi0G+0+jA9ZsXTw5igUBAkdw7yEOyjL4/jI/M3RoCcTikRCn35USVRdJv8X7GAL1rwNWj5zRvauDnKjlqK4ny+xnE0sABSP0TgMge3spDIHprabL0+aNeDeuKyhUquRcHoeIab4A0pDAdyZHFmQiJwoUWSXq10Ilm/jToCHNVV+xpAdmMz0niIYaSuD9PKvv4y+uOGDgQkCqyjlJq3wseR8hCidn3iDINR2Gf8vWXzm92syngOVdhi+6g8ZIG5PtkVXe0Dk5M4ZMmM= root@compute-vm-2-2-20-ssd-1741186332905"
